# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0004_auto_20170221_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtdcomment',
            name='followup',
            field=models.BooleanField(default=False, help_text='Notify follow-up comments'),
        ),
    ]
