# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 22:37
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuesBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='留言板标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='留言板')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '留言板',
                'verbose_name': '留言板',
            },
        ),
        migrations.CreateModel(
            name='MyPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('mypicture_cover', models.ImageField(upload_to='image/mypicture/cover', verbose_name='相册封面')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '我的相册',
                'ordering': ['-created_time'],
                'verbose_name': '我的相册',
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('profile', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='个人简介')),
            ],
            options={
                'verbose_name_plural': '个人简介',
                'verbose_name': '个人简介',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('photo', models.ImageField(upload_to='image/mypicture/photo', verbose_name='照片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('mypicture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.MyPicture', verbose_name='所属相册')),
            ],
            options={
                'verbose_name_plural': '相册照片',
                'ordering': ['-created_time'],
                'verbose_name': '相册照片',
            },
        ),
    ]
