# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypicture',
            name='mypicture_cover',
            field=models.ImageField(blank=True, null=True, upload_to='image/mypicture/cover', verbose_name='相册封面'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/mypicture/photo', verbose_name='照片'),
        ),
    ]
