# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('post', '0002_auto_20171027_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('profile', models.CharField(max_length=300, verbose_name='简介')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='image/subject', verbose_name='图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
            },
        ),
        migrations.CreateModel(
            name='SubjectBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='image/banner', verbose_name='图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='subject.Subject', verbose_name='专题')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='SubjectChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='章节名称')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='专题')),
            ],
            options={
                'verbose_name': '专题章节',
                'verbose_name_plural': '专题章节',
            },
        ),
        migrations.CreateModel(
            name='SubjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectChapter')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '专题明细',
                'verbose_name_plural': '专题明细',
            },
        ),
        migrations.CreateModel(
            name='SubjectStaticType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '专题状态',
                'verbose_name_plural': '专题状态',
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '专题类别',
                'verbose_name_plural': '专题类别',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='static',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectStaticType', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectType', verbose_name='分类'),
        ),
    ]
